# Generated by Django 3.1.12 on 2024-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55)),
                ('job_title', models.CharField(choices=[('Backend_Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Full_Stack_Developer', 'Full Stack Developer'), ('Data_Scientist', 'Data_Scientist'), ('DevOps_Engineer', 'DevOps Engineer'), ('QA_Engineer', 'QA_Engineer'), ('Project_Manager', 'Project Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('Fluter_Developer', 'Fluter_developer'), ('MERN Developer', 'MERN_developer'), ('Digital Marketing', 'Digital Marketing')], max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('employment_detail', models.TextField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('year_of_experience', models.CharField(blank=True, max_length=55, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='Resumes/')),
                ('Resume_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
